---
- hosts: localhost
  vars:
    sshkey: ".ssh/ansible_ed25519"
    tmp: "{{ playbook_dir }}/tmp"
  pre_tasks:
    - name: pre-run | Create temporary file
      tags:
        - install
        - dotfiles
      tempfile:
        state: file
        suffix: temp
      register: tempfile_ssh
      changed_when: false
    - name: pre-run | Temporarily install SSH key to tmp directory
      tags:
        - install
        - dotfiles
      ansible.builtin.copy:
        src: "{{ sshkey }}"
        dest: "{{ tempfile_ssh.path }}"
        mode: 0600
      changed_when: false
  tasks:
    - block:
        - name: placeholder
          tags: test
          debug:
            msg: test
      rescue:
        - name: error | Print when errors
          tags: always
          debug:
            msg: Encountered an error!
      always:
        - name: cleanup | Check if tmp directory exists
          tags: always
          stat:
            path: "{{ tempfile_ssh.path }}"
          register: tmp_stat
          changed_when: false
        - name: cleanup | Remove the temporary file
          tags: always
          file:
            path: "{{ tempfile_ssh.path }}"
            state: absent
          when: tmp_stat.stat.exists
          changed_when: false
