---
- hosts: localhost
  vars:
    sshkey: ".ssh/ansible_ed25519"
  pre_tasks:
    - name: pre-run | Create temporary file
      ansible.builtin.tempfile:
        state: file
        suffix: temp
      register: tempfile_ssh
      changed_when: false
      tags:
        - never
        - install
        - dotfiles
    - name: pre-run | Temporarily install SSH key to tmp directory
      ansible.builtin.copy:
        src: "{{ sshkey }}"
        dest: "{{ tempfile_ssh.path }}"
        mode: "0600"
      changed_when: false
      tags:
        - never
        - install
        - dotfiles
  tasks:
    - name: init | Load tasks
      tags:
        - never
      block:
        - name: core | Load
          ansible.builtin.import_tasks: tasks/core.yml
        - name: zsh | Load
          ansible.builtin.import_tasks: tasks/zsh.yml
        - name: dotfiles | Load
          ansible.builtin.import_tasks: tasks/dotfiles.yml
        - name: tools | Load
          ansible.builtin.import_tasks: tasks/tools.yml
        - name: wayland | Load
          ansible.builtin.import_tasks: tasks/wayland.yml
        - name: theme | Load
          ansible.builtin.import_tasks: tasks/theme.yml
        - name: media | Load
          ansible.builtin.import_tasks: tasks/media.yml
      rescue:
        - name: error | Print when errors
          ansible.builtin.debug:
            msg: Encountered an error!
          changed_when: false
          tags: always
      always:
        - name: cleanup | Remove all temporary files
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          with_fileglob:
            - "/tmp/ansible.*temp"
          changed_when: false
          tags: always
