---
- hosts: localhost
  vars:
    sshkey: ".ssh/ansible_ed25519"
  pre_tasks:
    - name: pre-run | Create temporary file
      tempfile:
        state: file
        suffix: temp
      register: tempfile_ssh
      changed_when: false
      tags:
        - install
        - dotfiles
    - name: pre-run | Temporarily install SSH key to tmp directory
      ansible.builtin.copy:
        src: "{{ sshkey }}"
        dest: "{{ tempfile_ssh.path }}"
        mode: 0600
      changed_when: false
      tags:
        - install
        - dotfiles
  tasks:
    - block:
        - import_tasks: tasks/dotfiles.yml
        - import_tasks: tasks/zsh.yml
      tags:
        - never
      rescue:
        - name: error | Print when errors
          debug:
            msg: Encountered an error!
          changed_when: false
          tags: always
      always:
        - name: cleanup | Remove all temporary files
          file:
            path: "{{ item }}"
            state: absent
          with_fileglob:
          - "/tmp/ansible.*temp"
          changed_when: false
          tags: always
