- name: dotfiles | Install package stow
  community.general.pacman:
    name: stow
    state: present
  tags:
    - install
    - dotfiles
- name: dotfiles | Clone dotfiles repo
  ansible.builtin.git:
    repo: git@github.com:sungyoonc/dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    key_file: "{{ tempfile_ssh.path }}"
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
