- name: dotfiles | Install stow package
  community.general.pacman:
    name: stow
    state: present
  become: true
  tags:
    - install
    - dotfiles
- name: dotfiles | Install dependencies
  community.general.pacman:
    name:
      # neovim
      - tree-sitter
      - ripgrep
      # usb auto detect (sway)
      - udisks2
      - udiskie
    state: present
  become: true
  tags:
    - install
    - dotfiles
- name: dotfiles | Clone dotfiles repo
  ansible.builtin.git:
    repo: git@github.com:sungyoonc/dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: true
    update: true
    key_file: "{{ tempfile_ssh.path }}"
    accept_hostkey: true
    version: main
  tags:
    - install
    - dotfiles
- name: dotfiles | Stow dotfiles
  shell: cd $HOME/.dotfiles/ && ./install
  tags:
    - install
    - dotfiles
